# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau = "luau-lang/luau@0.697.0"
lute = "luau-lang/lute@0.1.0-nightly.20251028"
wally = "UpliftGames/wally@0.3.2"
