name = "tkStudio"
version = 0
type = "plugin"
entry = "src/index.luau"

[[portals]]
project = "./src/"
roblox = "game.ReplicatedStorage.TK"

[[portals]]
project = "./packages"
roblox = "game.ReplicatedStorage.Packages"
external = true

[experimental]
profiling = true
