[package]
name = "tk_native"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
serde = "1.0.228"
serde_json = "1.0.148"

[target.'cfg(windows)'.dependencies.windows]
version = "0.62.2"
features = [
"Win32_Security_Credentials"
]

[lib]
crate-type = ["cdylib"]
bench = false
